name: Generate Changelog action

on:
  push:
    tags:
      - 'v*'

jobs:
  generate-changelog:
    runs-on: ubuntu-latest

    steps:
      - uses: hunghg255/changeloggithub-actions@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          from_branch: 'changelog-action'
          to_branch: 'main'
