name: Notification

on:
  push:
    branches:
      - noti

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build and lint
        run: |
          echo "Build and lint"

      - name: On Failure
        if: failure()
        uses: hunghg255/action-notifications@master
        with:
          discord_webhook: ${{ secrets.DISCORD_WEBHOOK }}
          slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
          title: "Deploy: Success"
          description: "Test deploy success"

  notifification:
      needs: deploy
      runs-on: ubuntu-latest

      steps:
        - uses: hunghg255/action-notifications@master
          if: always()
          with:
            discord_webhook: ${{ secrets.DISCORD_WEBHOOK }}
            slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
            title: "Deploy: Success"
            description: "Test deploy success"
